<?php
namespace Geissler\Converter\Model;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-05 at 12:36:08.
 */
class DatesTest extends TestCase
{
    /**
     * @var Dates
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Dates;
    }

    /**
     * @covers Geissler\Converter\Model\Dates::setDate
     * @covers Geissler\Converter\Model\Container::setData
     */
    public function testSetDate()
    {
        $this->assertInstanceOf('\Geissler\Converter\Model\Dates', $this->object->setDate(new Date()));
    }
}
