<?php

namespace Geissler\Converter;

use Geissler\Converter\Standard\Basic\StandardAbstract;
use Geissler\Converter\Standard\BibTeX\BibTeX;
use Geissler\Converter\Standard\CSL\CSL;
use Geissler\Converter\Standard\RIS\RIS;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-10 at 15:02:07.
 */
class ConverterTest extends TestCase
{

    /**
     * @var Converter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Converter;
    }

    /**
     * @covers       \Geissler\Converter\Converter::convert
     * @dataProvider dataProviderForConvert
     */
    public function testConvert(StandardAbstract $from, StandardAbstract $to, string $expected): void
    {
        $actual = $this->object->convert($from, $to);
        $this->assertEquals($expected, $actual);
    }

    public function dataProviderForConvert()
    {
        return [
            [
                new CSL(
                    '[
      {
          "id": "ITEM-1",
          "author" : [
             {
                "family": "Wallace-Hadrill",
                "given": "Andrew"
             },
             {
                "family": "Zanker",
                "given": "Paul"
             },
             {
                "family": "Boschung",
                "given": "Dieter"
             }
          ],
          "issued": {
              "date-parts": [
                  [
                      "2011"
                  ]
              ]
          },
          "title": "The monumental centre of Herculaneum. In search of the identities of the public buildings",
          "container-title" : "Journal of Roman archaeology",
          "volume" : "24",
          "page" : "121-160",
          "type": "article-journal"
      }]'
                ),
                new BibTeX(),
                <<<EXPECTED
                @article{article,\r
                author = {Wallace-Hadrill, Andrew and Zanker, Paul and Boschung, Dieter},\r
                year = {2011},\r
                pages = {121-160},\r
                title = {The monumental centre of Herculaneum. In search of the identities of the public buildings},\r
                booktitle = {Journal of Roman archaeology}\r
                }
                EXPECTED
                ,
            ],
            [
                new RIS(
                    <<<RIS
                        TY  - JOUR\r
                        TI  - Die Grundlage der allgemeinen Relativitätstheorie\r
                        AU  - Einstein, Albert\r
                        PY  - 1916\r
                        SP  - 769\r
                        EP  - 822\r
                        JO  - Annalen der Physik\r
                        VL  - 49\r
                        ER  - \r
                        RIS
                ),
                new BibTeX(),
                <<<EXPECTED
                    @article{article,\r
                    author = {Einstein, Albert},\r
                    year = {1916},\r
                    pages = {769-822},\r
                    title = {Die Grundlage der allgemeinen Relativitätstheorie},\r
                    volume = {49}\r
                    }
                    EXPECTED
                ,
            ],
            [
                new BibTeX(
                    <<<BIBTEX
                    @article{article,\r
                    author = {Einstein, Albert},\r
                    year = {1916},\r
                    pages = {769-822},\r
                    title = {Die Grundlage der allgemeinen Relativitätstheorie},\r
                    volume = {49}\r
                    }
                    BIBTEX
                ),
                new CSL(),
                '[{"type":"article","author":[{"family":"Einstein","given":"Albert"}],"issued":[{"year":"1916"}],"page":"769-822","page-first":"769","citation-label":"article","title":"Die Grundlage der allgemeinen Relativit\u00e4tstheorie"}]',
            ],
            [
                new BibTeX(
                    <<<BIXTEX
                    @article{article,
                    author = {Einstein, Albert},
                    year = {1916},
                    pages = {769-822},
                    title = {Die Grundlage der allgemeinen Relativitätstheorie},
                    volume = {49}
                    }
                    BIXTEX

                ),
                new CSL(),
                '[{"type":"article","author":[{"family":"Einstein","given":"Albert"}],"issued":[{"year":"1916"}],"page":"769-822","page-first":"769","citation-label":"article","title":"Die Grundlage der allgemeinen Relativit\u00e4tstheorie"}]',
            ],
        ];
    }

    /**
     * @covers \Geissler\Converter\Converter::convert
     */
    public function testDoNotConvert(): void
    {
        $this->assertEquals('Error! The data could not be parsed!', $this->object->convert(new BibTeX(), new RIS()));
    }
}
